# This is a basic workflow to help you get started with Actions

name: "sign_in"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "2 3,22 * * ?"  # scheduled everyday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      # Runs a single command using the runners shell
      - name: Set up python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.6

      - name: Sleep
        run: |
          python -m pip install --upgrade pip
          pip install requests
          echo "====Sleep===="
          python3 ./Sleep.py
          
      # Runs a set of commands using the runners shell
      - name: Run Announcement
        env:
          CorpId: ${{ secrets.CORPID }}
          CorpSecret: ${{ secrets.CORPSECRET }}
        run: |
          echo "====Announcement===="
          python3 ./Action.py
          echo "命令"